import { useState } from 'react'

const initialContent = {
  welcomeTitle: 'How was your experience?', welcomeSubtitle: 'Your feedback helps us make every interaction better.', question: 'How satisfied are you today?', options: ['Very dissatisfied', 'Dissatisfied', 'Neutral', 'Satisfied', 'Very satisfied'], comments: true, submitText: 'Send feedback', thankTitle: 'Thank you for sharing!', thankSubtitle: 'Your voice makes a difference to our team.', thankButton: 'Done',
}
const initialStyles = { background: '#fffaf3', title: '#162033', subtitle: '#667085', button: '#e56b4f', buttonText: '#ffffff', accent: '#e56b4f', mutedAccent: '#f2d6c5', fontSize: 18, weight: 600, radius: 18, buttonWidth: 100, buttonHeight: 52 }

function Icon({ children }) { return <span className="icon" aria-hidden="true">{children}</span> }
function Field({ label, hint, children }) { return <label className="field"><span className="field-label">{label}</span>{hint && <span className="field-hint">{hint}</span>}{children}</label> }
function TextInput({ value, onChange, placeholder }) { return <input className="text-input" value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} /> }
function ColorInput({ label, value, onChange }) { return <label className="color-row"><span>{label}</span><span className="color-control"><input type="color" value={value} onChange={(event) => onChange(event.target.value)} /><span>{value.toUpperCase()}</span></span></label> }

function ContentPanel({ content, setContent }) {
  const update = (key, value) => setContent((current) => ({ ...current, [key]: value }))
  const updateOption = (index, value) => update('options', content.options.map((option, optionIndex) => optionIndex === index ? value : option))
  const removeOption = (index) => update('options', content.options.filter((_, optionIndex) => optionIndex !== index))
  const addOption = () => update('options', [...content.options, `Option ${content.options.length + 1}`])
  return <div className="settings-stack">
    <section className="settings-section"><div className="section-heading"><div><span className="eyebrow">01 / Welcome screen</span><h2>First impression</h2></div><span className="section-number">A</span></div><Field label="Title"><TextInput value={content.welcomeTitle} onChange={(value) => update('welcomeTitle', value)} /></Field><Field label="Subtitle"><textarea className="text-input text-area" value={content.welcomeSubtitle} onChange={(event) => update('welcomeSubtitle', event.target.value)} /></Field></section>
    <section className="settings-section"><div className="section-heading"><div><span className="eyebrow">02 / Feedback screen</span><h2>Ask the question</h2></div><span className="section-number">B</span></div><Field label="Question"><TextInput value={content.question} onChange={(value) => update('question', value)} /></Field><div className="field"><div className="field-label-row"><span className="field-label">Answer options</span><span className="field-hint">{content.options.length} options</span></div><div className="option-list">{content.options.map((option, index) => <div className="option-row" key={`${index}-${option}`}><span className="drag">⠿</span><input className="text-input" value={option} onChange={(event) => updateOption(index, event.target.value)} /><button className="icon-button danger" onClick={() => removeOption(index)} aria-label={`Delete ${option}`}>×</button></div>)}</div><button className="add-button" onClick={addOption}><Icon>+</Icon> Add option</button></div><div className="toggle-row"><div><span className="field-label">Additional comments</span><span className="field-hint">Let people add context to their answer</span></div><button className={`toggle ${content.comments ? 'active' : ''}`} onClick={() => update('comments', !content.comments)} aria-label="Toggle comments"><span /></button></div><Field label="Submit button text"><TextInput value={content.submitText} onChange={(value) => update('submitText', value)} /></Field></section>
    <section className="settings-section"><div className="section-heading"><div><span className="eyebrow">03 / Thank you screen</span><h2>Close the loop</h2></div><span className="section-number">C</span></div><Field label="Media" hint="PNG, JPG, GIF or Lottie"><label className="upload-box"><span className="upload-mark">↥</span><span><strong>Drop artwork here</strong><small>or browse from your computer</small></span><input type="file" accept=".png,.jpg,.jpeg,.gif,.json" /></label></Field><Field label="Title"><TextInput value={content.thankTitle} onChange={(value) => update('thankTitle', value)} /></Field><Field label="Subtitle"><textarea className="text-input text-area" value={content.thankSubtitle} onChange={(event) => update('thankSubtitle', event.target.value)} /></Field><Field label="Button text"><TextInput value={content.thankButton} onChange={(value) => update('thankButton', value)} /></Field></section>
  </div>
}

function StylingPanel({ styles, setStyles }) {
  const update = (key, value) => setStyles((current) => ({ ...current, [key]: value }))
  return <div className="settings-stack"><section className="settings-section"><div className="section-heading"><div><span className="eyebrow">01 / Color palette</span><h2>Set the mood</h2></div><span className="section-number">A</span></div><ColorInput label="Background" value={styles.background} onChange={(value) => update('background', value)} /><ColorInput label="Title" value={styles.title} onChange={(value) => update('title', value)} /><ColorInput label="Subtitle" value={styles.subtitle} onChange={(value) => update('subtitle', value)} /><ColorInput label="Button" value={styles.button} onChange={(value) => update('button', value)} /><ColorInput label="Button text" value={styles.buttonText} onChange={(value) => update('buttonText', value)} /></section><section className="settings-section"><div className="section-heading"><div><span className="eyebrow">02 / Type & shape</span><h2>Make it feel yours</h2></div><span className="section-number">B</span></div><Range label="Font size" hint="Comfortable reading scale" value={styles.fontSize} suffix="px" min="14" max="24" onChange={(value) => update('fontSize', value)} /><Range label="Font weight" hint="Title and question weight" value={styles.weight} suffix="" min="400" max="800" step="100" onChange={(value) => update('weight', value)} /><Range label="Border radius" hint="Roundness of the card" value={styles.radius} suffix="px" min="0" max="32" onChange={(value) => update('radius', value)} /></section><section className="settings-section"><div className="section-heading"><div><span className="eyebrow">03 / Button & rating</span><h2>Polish the details</h2></div><span className="section-number">C</span></div><Range label="Button width" hint="Relative to the popup" value={styles.buttonWidth} suffix="%" min="60" max="100" onChange={(value) => update('buttonWidth', value)} /><Range label="Button height" hint="Tap target size" value={styles.buttonHeight} suffix="px" min="40" max="64" onChange={(value) => update('buttonHeight', value)} /><ColorInput label="Selected rating" value={styles.accent} onChange={(value) => update('accent', value)} /><ColorInput label="Unselected rating" value={styles.mutedAccent} onChange={(value) => update('mutedAccent', value)} /></section></div>
}
function Range({ label, hint, value, suffix, min, max, step = 1, onChange }) { return <><div className="range-row"><div><span className="field-label">{label}</span><span className="field-hint">{hint}</span></div><output>{value}{suffix}</output></div><input type="range" min={min} max={max} step={step} value={value} onChange={(event) => onChange(Number(event.target.value))} /></> }

function Preview({ content, styles }) {
  const [screen, setScreen] = useState('feedback'); const [rating, setRating] = useState(4)
  const previewStyle = { '--preview-bg': styles.background, '--preview-title': styles.title, '--preview-subtitle': styles.subtitle, '--preview-button': styles.button, '--preview-button-text': styles.buttonText, '--preview-accent': styles.accent, '--preview-muted': styles.mutedAccent, '--preview-radius': `${styles.radius}px`, '--preview-weight': styles.weight, '--preview-button-width': `${styles.buttonWidth}%`, '--preview-button-height': `${styles.buttonHeight}px` }
  return <div className="preview-column">
    <div className="preview-topline"><div><span className="eyebrow">Live preview</span><h2>See it in context</h2></div><span className="live-pill"><i /> Live</span></div>
    <div className="device-wrap"><div className="device"><div className="device-camera" /><div className="device-screen">
      <div className="status-bar"><span>9:41</span><span>▮▮▮ ◉</span></div>
      <div className="app-backdrop"><div className="fake-nav"><span className="fake-logo">P</span><span className="fake-lines"><i /><i /><i /></span></div><div className="fake-content"><span /><span /><span /><span /></div><div className="popup-scrim" />
        <div className="popup" style={previewStyle}>
          {screen === 'feedback' ? <>
            <div className="popup-icon">✦</div><h3>{content.welcomeTitle}</h3><p>{content.welcomeSubtitle}</p>
            <div className="question-block"><strong>{content.question}</strong><div className="stars">{[1, 2, 3, 4, 5].map((star) => <button key={star} className={star <= rating ? 'selected' : ''} onClick={() => setRating(star)} aria-label={`Rate ${star} out of 5`}>★</button>)}</div><div className="rating-labels"><span>Not great</span><span>Loved it</span></div></div>
            {content.comments && <div className="comment-placeholder">Anything else you want to share?</div>}
            <button className="preview-button" onClick={() => setScreen('thankyou')}>{content.submitText}<span>→</span></button><button className="skip-button">Maybe later</button>
          </> : <>
            <div className="success-icon">✓</div><h3>{content.thankTitle}</h3><p>{content.thankSubtitle}</p><button className="preview-button" onClick={() => setScreen('feedback')}>{content.thankButton}<span>→</span></button>
          </>}
        </div>
      </div>
    </div><div className="home-indicator" /></div></div>
    <span className="preview-caption">Interactive preview · click a star or submit</span>
  </div>
}

export default function App() { const [tab, setTab] = useState('content'); const [content, setContent] = useState(initialContent); const [styles, setStyles] = useState(initialStyles); return <div className="app-shell"><header className="topbar"><a className="brand" href="/" aria-label="Pulseframe home"><span className="brand-mark">P</span><span>pulseframe</span></a><div className="breadcrumbs"><span>Campaigns</span><b>/</b><strong>New CSAT campaign</strong></div><div className="top-actions"><span className="saved"><i /> All changes saved</span><button className="avatar">AV</button></div></header><main className="workspace"><div className="workspace-intro"><div><span className="eyebrow">Campaign builder / Draft</span><h1>Make feedback feel <em>human.</em></h1><p>Design a thoughtful CSAT moment your customers will actually want to answer.</p></div><button className="close-button" aria-label="Close builder">×</button></div><div className="builder-grid"><div className="editor"><div className="tabs" role="tablist"><button className={tab === 'content' ? 'active' : ''} onClick={() => setTab('content')}><Icon>✦</Icon> Content <span>3</span></button><button className={tab === 'styling' ? 'active' : ''} onClick={() => setTab('styling')}><Icon>◒</Icon> Styling <span>3</span></button></div><div className="tab-intro"><span className="tab-icon">{tab === 'content' ? '✦' : '◒'}</span><div><h2>{tab === 'content' ? 'Tell your story' : 'Shape the experience'}</h2><p>{tab === 'content' ? 'Write the words that guide your customer through the moment.' : 'Fine-tune colors, type, and proportions to match your brand.'}</p></div></div>{tab === 'content' ? <ContentPanel content={content} setContent={setContent} /> : <StylingPanel styles={styles} setStyles={setStyles} />}</div><Preview content={content} styles={styles} /></div></main><footer className="footer"><span><strong>Pulseframe</strong> campaign builder</span><span>Built for better conversations <b>✦</b></span></footer></div> }